{
 "title": "Github Copilot Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "language",
    "label": "Language",
    "query": {
     "query": "label_values(github_copilot_suggestions_count_breakdown, language)"
    }
   },
   {
    "name": "editor",
    "label": "Editor",
    "query": {
     "query": "label_values(github_copilot_suggestions_count_breakdown, editor)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Users stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Github Copilot seats",
   "type": "stat",
   "description": "Number of seats that occupied",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_copilot_total_seats_occupied"
    }
   ]
  },
  {
   "title": "Github Copilot Active Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_copilot_total_active_users"
    }
   ]
  },
  { "title": "Copilot Total stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Github Copilot suggestions",
   "type": "stat",
   "description": "Total number of suggestions made by GitHub Copilot last day.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_copilot_total_suggestions_count"
    }
   ]
  },
  {
   "title": "Number of acceptance by users",
   "type": "stat",
   "description": "Total number of suggestions accepted by users last day.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_copilot_total_acceptances_count"
    }
   ]
  },
  {
   "title": "Number of seggested lines",
   "type": "stat",
   "description": "Total number of lines suggested by GitHub Copilot last day.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_copilot_total_lines_suggested"
    }
   ]
  },
  {
   "title": "Number of lines accepted by users",
   "type": "stat",
   "description": "Total number of lines accepted by users last day.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_copilot_total_lines_accepted"
    }
   ]
  },
  {
   "title": "Language usage stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active users per language",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (language) (github_copilot_active_users_breakdown)",
       "legendFormat": "{{language}}"
      }
     ]
    },
    {
     "title": "Acceptance rate per language",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 10, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (language) (github_copilot_acceptances_count_breakdown/github_copilot_suggestions_count_breakdown)",
       "legendFormat": "{{language}}"
      }
     ]
    }
   ]
  },
  {
   "title": "${language} language stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "language",
   "collapsed": true,
   "panels": [
    {
     "title": "Copilot suggestion for ${language}",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "github_copilot_suggestions_count_breakdown{language=\"${language}\"}",
       "legendFormat": "{{editor}}"
      }
     ]
    },
    {
     "title": "Accepted ${language} suggestions by users",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "github_copilot_acceptances_count_breakdown{language=\"${language}\"}",
       "legendFormat": "{{editor}}"
      }
     ]
    },
    {
     "title": "Active users of ${language}",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "github_copilot_active_users_breakdown{language=\"${language}\"}",
       "legendFormat": "{{editor}}"
      }
     ]
    },
    {
     "title": "Acceptance rate for ${language}",
     "type": "piechart",
     "description": "Rate of accepted lines for ${language}",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(github_copilot_lines_suggested_breakdown{language=\"${language}\"})",
       "legendFormat": "suggested"
      },
      {
       "expr": "sum(github_copilot_lines_accepted_breakdown{language=\"${language}\"})",
       "legendFormat": "accepted"
      }
     ]
    }
   ]
  }
 ]
}